### ISSUE TITLE
Update Setup Instructions

### ISSUE THREAD

**Issue by aswad546** [microsoft/OmniParser#102]
Hello,

Thank you for making this wonderful tool. I was attempting to set it up on my machine and it seems that the setup instructions are incomplete in the readme and vague. I am having trouble converting safe tensor files to pt. Could you please give more details so I can setup easier.

Thanks,
Aswad

**Comment by aswad546** [comment]
python weights/convert_safetensor_to_pt.py
usage: convert_safetensor_to_pt.py [-h] --weights_dir WEIGHTS_DIR
convert_safetensor_to_pt.py: error: the following arguments are required: --weights_dir

What directory is this expecting

**Comment by aswad546** [comment]
I believe the model_v1_5.pt file is to replace the best.pt file in the gradiodemo but after doing so I get the following error:

`yolo_model = get_yolo_model(model_path='weights/icon_detect_v1_5/model_v1_5.pt')`


This is my error running this file now:
Traceback (most recent call last):
  File "/u1/a8tariq/Llama vision/OmniParser/gradio_demo.py", line 15, in <module>
    yolo_model = get_yolo_model(model_path='weights/icon_detect_v1_5/model_v1_5.pt')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u1/a8tariq/Llama vision/OmniParser/utils.py", line 73, in get_yolo_model
    model = YOLO(model_path)
            ^^^^^^^^^^^^^^^^
  File "/u1/a8tariq/.conda/envs/vllm/lib/python3.12/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/u1/a8tariq/.conda/envs/vllm/lib/python3.12/site-packages/ultralytics/engine/model.py", line 142, in __init__
    self._load(model, task=task)
  File "/u1/a8tariq/.conda/envs/vllm/lib/python3.12/site-packages/ultralytics/engine/model.py", line 229, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u1/a8tariq/.conda/envs/vllm/lib/python3.12/site-packages/ultralytics/nn/tasks.py", line 788, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/u1/a8tariq/.conda/envs/vllm/lib/python3.12/site-packages/ultralytics/nn/tasks.py", line 714, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u1/a8tariq/.conda/envs/vllm/lib/python3.12/site-packages/torch/serialization.py", line 1360, in load
    return _load(
           ^^^^^^
  File "/u1/a8tariq/.conda/envs/vllm/lib/python3.12/site-packages/torch/serialization.py", line 1848, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "/u1/a8tariq/.conda/envs/vllm/lib/python3.12/site-packages/torch/serialization.py", line 1837, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'C3k2' on <module 'ultralytics.nn.modules.block' from '/u1/a8tariq/.conda/envs/vllm/lib/python3.12/site-packages/ultralytics/nn/modules/block.py'>

**Comment by arsh837** [comment]
upgrading the ultralytics library solves this issue
pip install --upgrade ultralytics

**Comment by yadong-lu** [comment]
@aswad546 thanks for noting the error. I have updated the readme to accommodate the v1.5 ckpt. Please let me know if you have any issues. Thanks
