### ISSUE TITLE
Can't get attribute 'C3k2'

### ISSUE THREAD

**Issue by lishaozheng** [microsoft/OmniParser#104]
We haven't changed to GPU yet, and run --icon_detect_model weights/icon_detect/best.pt no problem

python gradio_demo.py --icon_detect_model weights/icon_detect_v1_5/model_v1_5.pt --icon_caption_model florence2

python gradio_demo.py --icon_detect_model weights/icon_detect_v1_5/model_v1_5.pt --icon_caption_model florence2
[2024-12-21 19:35:12,731] [ WARNING] easyocr.py:80 - Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
Traceback (most recent call last):
  File "G:\LiProbject\OmniParser\gradio_demo.py", line 72, in <module>
    yolo_model = get_yolo_model(model_path=icon_detect_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\LiProbject\OmniParser\utils.py", line 73, in get_yolo_model
    model = YOLO(model_path)
            ^^^^^^^^^^^^^^^^
  File "I:\ProgramData\anaconda3\envs\omni\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "I:\ProgramData\anaconda3\envs\omni\Lib\site-packages\ultralytics\engine\model.py", line 142, in __init__
    self._load(model, task=task)
  File "I:\ProgramData\anaconda3\envs\omni\Lib\site-packages\ultralytics\engine\model.py", line 229, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\ProgramData\anaconda3\envs\omni\Lib\site-packages\ultralytics\nn\tasks.py", line 788, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\ProgramData\anaconda3\envs\omni\Lib\site-packages\ultralytics\nn\tasks.py", line 714, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\ProgramData\anaconda3\envs\omni\Lib\site-packages\torch\serialization.py", line 1360, in load
    return _load(
           ^^^^^^
  File "I:\ProgramData\anaconda3\envs\omni\Lib\site-packages\torch\serialization.py", line 1848, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "I:\ProgramData\anaconda3\envs\omni\Lib\site-packages\torch\serialization.py", line 1837, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'C3k2' on <module 'ultralytics.nn.modules.block' from 'I:\\ProgramData\\anaconda3\\envs\\omni\\Lib\\site-packages\\ultralytics\\nn\\modules\\block.py'>

**Comment by sjlnl** [comment]
how did you solve that error?

**Comment by gaoyuqiang** [comment]
how did you solve that error?

**Comment by gaoyuqiang** [comment]
> 你是如何解决该错误的？

pip install --upgrade ultralytics
