### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/weights/icon_caption_florence/resolve/main/config.json

### ISSUE THREAD

**Issue by mtwichan** [microsoft/OmniParser#26]
Hey guys, I'm trying to run the `gradio_demo.py` and `demo.ipynb` locally and it looks like the repository that the demo code relies on is no longer available.

Can you please fix this? Or let me know how to run it?

Thanks.

Error Message:

```
Repository Not Found for url: https://huggingface.co/weights/icon_caption_florence/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/matthew/Desktop/omniparser/OmniParser/gradio_demo.py", line 16, in <module>
    caption_model_processor = get_caption_model_processor(model_name="florence2", model_name_or_path="weights/icon_caption_florence")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Desktop/omniparser/OmniParser/utils.py", line 54, in get_caption_model_processor
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, torch_dtype=torch.float32, trust_remote_code=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Desktop/omniparser/OmniParser/venv/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/Users/matthew/Desktop/omniparser/OmniParser/venv/lib/python3.11/site-packages/transformers/utils/hub.py", line 426, in cached_file
    raise EnvironmentError(
OSError: weights/icon_caption_florence is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
```

**Comment by mtwichan** [comment]
Fixed by:
1. Running from root: `huggingface-cli download microsoft/OmniParser --local-dir ./weights --local_dir_use_symlinks false`
2. Adding this missing file back to `weights/icon_detect`: `https://github.com/microsoft/OmniParser/blob/8a3c07d0cdb726d51ca513c446316b28118364d1/weights/icon_detect/best.pt`

**Comment by abrichr** [comment]
See https://github.com/microsoft/OmniParser/pull/52/files for download.py script and Dockerfile.
