### ISSUE TITLE
Error loading the icon_caption_blip2 model.

### ISSUE THREAD

**Issue by VandyLu** [microsoft/OmniParser#4]
I found that the icon_caption_blip2_model on the huggingface cannot be correctly loaded. The code "model = Blip2ForConditionalGeneration.from_pretrained(model_name_or_path, device_map=None, torch_dtype=torch.float16)" get the following errors:

Error details:

          Traceback (most recent call last):
          File "/home/llm/miniconda3/envs/seeclick/lib/python3.8/site-packages/transformers/modeling_utils.py", line 533, in load_state_dict
            return torch.load(
          File "/home/llm/miniconda3/envs/seeclick/lib/python3.8/site-packages/torch/serialization.py", line 1005, in load
            with _open_zipfile_reader(opened_file) as opened_zipfile:
          File "/home/llm/miniconda3/envs/seeclick/lib/python3.8/site-packages/torch/serialization.py", line 457, in __init__
            super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
        RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/home/llm/miniconda3/envs/seeclick/lib/python3.8/site-packages/transformers/modeling_utils.py", line 542, in load_state_dict
            if f.read(7) == "version":
          File "/home/llm/miniconda3/envs/seeclick/lib/python3.8/codecs.py", line 322, in decode
            (result, consumed) = self._buffer_decode(data, self.errors, final)
        UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "main.py", line 12, in <module>
            caption_model_processor = get_caption_model_processor(model_name_or_path="./OmniParser/icon_caption_blip2/", device=device)
          File "./OmniParser/utils.py", line 46, in get_caption_model_processor
            model = Blip2ForConditionalGeneration.from_pretrained(
          File "/home/llm/miniconda3/envs/seeclick/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3677, in from_pretrained
            ) = cls._load_pretrained_model(
          File "/home/llm/miniconda3/envs/seeclick/lib/python3.8/site-packages/transformers/modeling_utils.py", line 4084, in _load_pretrained_model
            state_dict = load_state_dict(shard_file, is_quantized=is_quantized)
          File "/home/llm/miniconda3/envs/seeclick/lib/python3.8/site-packages/transformers/modeling_utils.py", line 554, in load_state_dict
            raise OSError(
        OSError: Unable to load weights from pytorch checkpoint file for './OmniParser/icon_caption_blip2/pytorch_model-00001-of-00002.bin' at './OmniParser/icon_caption_blip2/pytorch_model-00001-of-00002.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

I tried different transformers versions and created a new conda env, but the error still occured. I guess it's casued by a corrupted file in the uploaded huggingface model. Would you please take a look at the files?

**Comment by VandyLu** [comment]
It seems to be an issue with my local git-lfs. I download the file manually and it works well.
